#!/usr/bin/env bash
#This script install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
sudo sh -c "echo 'Holberton School' > /var/www/html/index.nginx-debian.html"
