#!/usr/bin/env bash
#This script install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
sudo sh -c "echo 'Holberton School' > /var/www/html/index.nginx-debian.html"
new_string="server_name _;\nrewrite    ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -ie "s/^server_name _;/$new_string/g" /etc/nginx/sites-available/default
sudo service nginx restart
