#!/usr/bin/env bash
# This script install HAproxy
sudo apt-get update
sudo apt-get install haproxy=1.6.\*
echo -e "frontend haproxynode
        bind *:80
        mode http
        default_backend backendnodes

backend backendnodes
        balance roundrobin
        option forwardfor
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
        option httpchk HEAD / HTTP/1.1\r\nHost:localhost
        server node1 35.231.144.217:80 check
        server node2 35.237.94.227:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
