#!/usr/bin/env bash
# This script install HAproxy
sudo apt-get update -y
sudo apt-get install haproxy=1.6.\* -y
echo "frontend haproxynode
        bind *:80
        mode http
        default_backend backendnodes" >> /etc/haproxy/haproxy.cfg

echo "backend backendnodes
        balance roundrobin
        server node1 35.231.144.217:80 check
        server node2 35.237.94.227:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
