#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely
path="/var/run/holbertonscript.pid"
sudo sh -c "echo $$ > $path"
trap 'echo I hate the kill command && sudo sh -c "rm $path" && exit' SIGTERM
trap "echo Y U no love me?!" SIGINT
trap 'sudo sh -c "rm $path" && exit' SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
