#!/usr/bin/env bash
# This File manage process with start | stop | restat
start()
{
  ./manage_my_process &
  sudo sh -c "echo $! > /var/run/my_process.pid"
}

stop()
{
  kill "$(cat /var/run/my_process.pid)"
  sudo sh -c "rm /var/run/my_process.pid"
}
case "$1" in
  start)
    start
    echo "manage_my_process started"
    ;;
  stop)
    stop
    echo "manage_my_process stopped"
    ;;
  restart)
    stop
    sleep 2
    start
    echo "manage_my_process restarted"
    ;;
    *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
esac
